In [23]:
import yfinance as yf

In [34]:
NVDA = yf.Ticker('NVDA')

In [35]:
NVDA.info

{'address1': '2788 San Tomas Expressway',
 'city': 'Santa Clara',
 'state': 'CA',
 'zip': '95051',
 'country': 'United States',
 'phone': '408 486 2000',
 'website': 'https://www.nvidia.com',
 'industry': 'Semiconductors',
 'industryKey': 'semiconductors',
 'industryDisp': 'Semiconductors',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "NVIDIA Corporation provides graphics and compute and networking solutions in the United States, Taiwan, China, Hong Kong, and internationally. The Graphics segment offers GeForce GPUs for gaming and PCs, the GeForce NOW game streaming service and related infrastructure, and solutions for gaming platforms; Quadro/NVIDIA RTX GPUs for enterprise workstation graphics; virtual GPU or vGPU software for cloud-based visual and virtual computing; automotive platforms for infotainment systems; and Omniverse software for building and operating metaverse and 3D internet applications. The Compute & Networking segment comprises Data Center computing platforms and end-to-end networking platforms, including Quantum for InfiniBand and Spectrum for Ethernet; NVIDIA DRIVE automated-driving platform and automotive development agreements; Jetson robotics and other embedded platforms; NVIDIA AI Enterprise and other software; and DGX Cloud software and services. The company's products are used in gaming, professional visualization, data center, and automotive markets. It sells its products to original equipment manufacturers, original device manufacturers, system integrators and distributors, independent software vendors, cloud service providers, consumer internet companies, add-in board manufacturers, distributors, automotive manufacturers and tier-1 automotive suppliers, and other ecosystem participants. NVIDIA Corporation was incorporated in 1993 and is headquartered in Santa Clara, California.",
 'fullTimeEmployees': 29600,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jen-Hsun  Huang',
   'age': 60,
   'title': 'Co-Founder, CEO, President & Director',
   'yearBorn': 1963,
   'fiscalYear': 2024,
   'totalPay': 7491487,
   'exercisedValue': 217327152,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Colette M. Kress',
   'age': 56,
   'title': 'Executive VP & CFO',
   'yearBorn': 1967,
   'fiscalYear': 2024,
   'totalPay': 1510765,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Debora  Shoquist',
   'age': 68,
   'title': 'Executive Vice President of Operations',
   'yearBorn': 1955,
   'fiscalYear': 2024,
   'totalPay': 1371266,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Timothy S. Teter',
   'age': 56,
   'title': 'Executive VP, General Counsel & Secretary',
   'yearBorn': 1967,
   'fiscalYear': 2024,
   'totalPay': 1360939,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ajay K. Puri',
   'age': 68,
   'title': 'Executive Vice President of Worldwide Field Operations',
   'yearBorn': 1955,
   'fiscalYear': 2024,
   'totalPay': 2295097,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris A. Malachowsky',
   'title': 'Co-Founder',
   'fiscalYear': 2024,
   'totalPay': 320000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Donald F. Robertson Jr.',
   'age': 54,
   'title': 'VP & Chief Accounting Officer',
   'yearBorn': 1969,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Prof. William J. Dally Ph.D.',
   'age': 62,
   'title': 'Chief Scientist & Senior VP of Research',
   'yearBorn': 1961,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Simona  Jankowski C.F.A., J.D.',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 10,
 'compensationRisk': 6,
 'shareHolderRightsRisk': 6,
 'overallRisk': 8,
 'governanceEpochDate': 1719792000,
 'compensationAsOfEpochDate': 1735603200,
 'irWebsite': 'http://phx.corporate-ir.net/phoenix.zhtml?c=116466&p=irol-IRHome',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 122.67,
 'open': 121.67,
 'dayLow': 121.36,
 'dayHigh': 128.28,
 'regularMarketPreviousClose': 122.67,
 'regularMarketOpen': 121.67,
 'regularMarketDayLow': 121.36,
 'regularMarketDayHigh': 128.28,
 'dividendRate': 0.04,
 'dividendYield': 0.00029999999,
 'exDividendDate': 1718064000,
 'payoutRatio': 0.0094,
 'fiveYearAvgDividendYield': 0.12,
 'beta': 1.68,
 'trailingPE': 75.01754,
 'forwardPE': 37.840706,
 'volume': 209606652,
 'regularMarketVolume': 209606652,
 'averageVolume': 422844009,
 'averageVolume10days': 372517430,
 'averageDailyVolume10Day': 372517430,
 'marketCap': 3155470057472,
 'fiftyTwoWeekLow': 39.23,
 'fiftyTwoWeekHigh': 140.76,
 'priceToSalesTrailing12Months': 39.55512,
 'fiftyDayAverage': 107.31826,
 'twoHundredDayAverage': 72.55581,
 'trailingAnnualDividendRate': 0.016,
 'trailingAnnualDividendYield': 0.00013043125,
 'currency': 'USD',
 'enterpriseValue': 3135487082496,
 'profitMargins': 0.53398,
 'floatShares': 23606406000,
 'sharesOutstanding': 24598300672,
 'sharesShort': 315033985,
 'sharesShortPriorMonth': 278905720,
 'sharesShortPreviousMonthDate': 1715731200,
 'dateShortInterest': 1718323200,
 'sharesPercentSharesOut': 0.0128,
 'heldPercentInsiders': 0.04309,
 'heldPercentInstitutions': 0.6753,
 'shortRatio': 0.72,
 'shortPercentOfFloat': 0.0134000005,
 'impliedSharesOutstanding': 24925200384,
 'bookValue': 1.998,
 'priceToBook': 64.2042,
 'lastFiscalYearEnd': 1706400000,
 'nextFiscalYearEnd': 1738022400,
 'mostRecentQuarter': 1714262400,
 'earningsQuarterlyGrowth': 6.284,
 'netIncomeToCommon': 42597998592,
 'trailingEps': 1.71,
 'forwardEps': 3.39,
 'pegRatio': 1.18,
 'lastSplitFactor': '10:1',
 'lastSplitDate': 1717977600,
 'enterpriseToRevenue': 39.305,
 'enterpriseToEbitda': 63.632,
 '52WeekChange': 2.0181398,
 'SandP52WeekChange': 0.25871396,
 'lastDividendValue': 0.01,
 'lastDividendDate': 1718064000,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'NVDA',
 'underlyingSymbol': 'NVDA',
 'shortName': 'NVIDIA Corporation',
 'longName': 'NVIDIA Corporation',
 'firstTradeDateEpochUtc': 917015400,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': '7f5f6a07-b148-30f4-98a2-2caa3df2aed0',
 'messageBoardId': 'finmb_32307',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 128.28,
 'targetHighPrice': 186.07,
 'targetLowPrice': 46.8,
 'targetMeanPrice': 120.51,
 'targetMedianPrice': 120.95,
 'recommendationMean': 1.8,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 48,
 'totalCash': 31438000128,
 'totalCashPerShare': 1.278,
 'ebitda': 49274998784,
 'totalDebt': 11237000192,
 'quickRatio': 2.877,
 'currentRatio': 3.529,
 'totalRevenue': 79773999104,
 'debtToEquity': 22.866,
 'revenuePerShare': 3.234,
 'returnOnAssets': 0.49103,
 'returnOnEquity': 1.15658,
 'freeCashflow': 29023750144,
 'operatingCashflow': 40524001280,
 'earningsGrowth': 6.5,
 'revenueGrowth': 2.621,
 'grossMargins': 0.75286,
 'ebitdaMargins': 0.61768,
 'operatingMargins': 0.64925003,
 'financialCurrency': 'USD',
 'trailingPegRatio': 1.4572}

In [36]:
df = NVDA.history(start ="2020-01-01", end ="2024-07-05")

In [37]:
#Head displaying the first 5 rows of which would be from start date 
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-01-02 00:00:00-05:00,5.944750,5.973633,5.894204,5.973633,237536000,0.0,0.0
2020-01-03 00:00:00-05:00,5.853867,5.921843,5.828967,5.878019,205384000,0.0,0.0
2020-01-06 00:00:00-05:00,5.784645,5.907897,5.758500,5.902668,262636000,0.0,0.0
2020-01-07 00:00:00-05:00,5.931055,6.019947,5.885987,5.974132,314856000,0.0,0.0
2020-01-08 00:00:00-05:00,5.969899,6.026670,5.929811,5.985337,277108000,0.0,0.0

In [38]:
#Tail displaying the last 5 rows of which would be from end date 
df.tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-06-27 00:00:00-04:00,124.099998,126.410004,122.919998,123.989998,252571700,0.0,0.0
2024-06-28 00:00:00-04:00,124.580002,127.709999,122.750000,123.540001,315516700,0.0,0.0
2024-07-01 00:00:00-04:00,123.470001,124.839996,118.830002,124.300003,284885500,0.0,0.0
2024-07-02 00:00:00-04:00,121.129997,123.410004,121.029999,122.669998,218374000,0.0,0.0
2024-07-03 00:00:00-04:00,121.660004,128.279999,121.360001,128.279999,215749000,0.0,0.0

In [41]:
#reccomendations from agencies with time periods
NVDA.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m          7   14    15     1           1
1    -1m         20   33     4     0           0
2    -2m         20   34     4     0           0
3    -3m         12   21    12     2           0

In [42]:
NVDA.calendar

{'Dividend Date': datetime.date(2024, 6, 28),
 'Ex-Dividend Date': datetime.date(2024, 6, 11),
 'Earnings Date': [datetime.date(2024, 8, 21), datetime.date(2024, 8, 26)],
 'Earnings High': 0.66,
 'Earnings Low': 0.56,
 'Earnings Average': 0.59,
 'Revenue High': 28334400000,
 'Revenue Low': 24951600000,
 'Revenue Average': 26406100000}